INSERT INTO public."Department" ("name") VALUES
	 ('Ban Giám Đốc Công ty'),
	 ('Ban Giám Đốc Bệnh viện'),
	 ('Khoa Phẫu thuật thẩm mỹ'),
	 ('Khoa Khám bệnh - Cấp cứu'),
	 ('Khoa Gây mê hồi sức'),
	 ('Khoa Da liễu'),
	 ('Khoa Răng Hàm Mặt'),
	 ('Khoa Chuẩn đoán hình ảnh'),
	 ('Khoa Dược - Vật tư y tế'),
	 ('Phòng Điều Dưỡng');
INSERT INTO public."Department" ("name") VALUES
	 ('Khoa Xét nghiệm'),
	 ('Bộ phận Phun xăm'),
	 ('Phòng Kế toán'),
	 ('Phòng Gội Đầu/Nail'),
	 ('Phòng Nhân sự'),
	 ('Bộ phận Kỹ thuật'),
	 ('Phòng Kế hoạch Tổng hợp'),
	 ('Bộ Phận Tư Vấn Online'),
	 ('Phòng Marketing'),
	 ('Bộ phận Tư vấn');
INSERT INTO public."Department" ("name") VALUES
	 ('Bộ phận CSKH'),
	 ('Bộ phận Thu Ngân'),
	 ('Bộ phận Lễ tân'),
	 ('Bộ phận Chăm sóc khách hàng hậu phẫu ca ngày'),
	 ('Bộ phận Chăm sóc khách hàng hậu phẫu ca đêm'),
	 ('Bộ phận Hộ lý'),
	 ('Bộ phận bảo vệ'),
	 ('Khác');



     INSERT INTO public."LaborNature" ("name") VALUES
	 ('Học việc'),
	 ('Thử việc'),
	 ('Chính thức'),
	 ('Tạm đình chỉ công việc'),
	 ('Nghỉ thai sản'),
	 ('Đang làm thủ tục nghỉ việc'),
	 ('Khác');



     INSERT INTO public."jobPosition" ("name") VALUES
        ('Tổng Giám đốc'),
        ('Chủ tịch HĐQT'),
        ('Phó Tổng giám đốc'),
        ('Giám đốc (Đại diện)'),
        ('Trợ lý Chủ tịch hội đồng quản trị'),
        ('Giám đốc Chuyên môn'),
        ('Phó Giám đốc Chuyên môn/Trưởng khoa KBCC'),
        ('Trưởng Khoa Phẫu thuật Thẩm mỹ'),
        ('Phó khoa Phẫu thuật Thẩm mỹ'),
        ('Bác sĩ KB-CB chuyên khoa PTTH'),
        ('Bác sĩ phẫu thuật tạo hình thẩm mỹ'),
        ('Bác sĩ KB-CB chuyên khoa Ngoại'),
        ('Trưởng khoa Gây mê hồi sức'),
        ('Bác sĩ KB-CB Chuyên khoa Gây mê hồi sức'),
        ('Nha sĩ'),
        ('Phụ tá'),
        ('Nhân viên Lễ tân'),
        ('Bác sĩ Răng Hàm Mặt'),
        ('Trưởng Khoa Da liễu'),
        ('Bác sĩ KB-CB chuyên khoa Da liễu'),
        ('Trưởng khoa Chuẩn đoán hình ảnh'),
        ('Bác sĩ chuyên khoa Chẩn đoán hình ảnh'),
        ('KTV Chẩn đoán hình ảnh'),
        ('Kỹ thuật viên Chẩn đoán hình ảnh'),
        ('Trưởng khoa Xét nghiệm'),
        ('KTV Xét nghiệm'),
        ('Kỹ thuật viên Gây Mê'),
        ('Bác sỹ điều trị'),
        ('Phó khoa Khám bệnh - Cấp cứu'),
        ('Thủ Kho-CV tư Vấn'),
        ('Trưởng khoa Dược - Vật tư y tế'),
        ('Dược sĩ'),
        ('Thủ Kho Dược'),
        ('Điều dưỡng trưởng'),
        ('Điều dưỡng viên'),
        ('Tổ trưởng Tổ dinh dưỡng'),
        ('Kỹ thuật viên Chăm sóc da'),
        ('Kỹ thuật viên gội đầu'),
        ('Kỹ thuật viên Nail'),
        ('Kỹ thuật viên Phun xăm'),
        ('Trưởng bộ phận Phun xăm'),
        ('Giám đốc Tài chính - Kế toán trưởng'),
        ('Chuyên viên Kế Toán'),
        ('Giám đốc Nhân sự'),
        ('Trưởng phòng HCNS'),
        ('Chuyên viên HCNS'),
        ('Trưởng bộ phận Kỹ thuật'),
        ('Chuyên viên Kỹ thuật'),
        ('Trưởng phòng Kế hoạch Tổng hợp'),
        ('Chuyên viên Kế Hoạch tổng hợp'),
        ('Thư ký Y khoa'),
        ('Trưởng bộ phận tư vấn online'),
        ('Chuyên viên tư vấn Online'),
        ('Nhân viên Admin'),
        ('Giám đốc sáng tạo kiêm phụ trách phòng Marketing'),
        ('Chuyên viên Thiết kế đồ họa'),
        ('Chuyên viên Media'),
        ('Trưởng Bộ phận Tư vấn'),
        ('Giám Đốc trung tâm CSKH'),
        ('Trưởng Bộ phận CSKH kiêm Chuyên viên Tư vấn'),
        ('Chuyên viên CSKH'),
        ('Chuyên viên Tư vấn'),
        ('Trưởng bộ phận Thu ngân'),
        ('Nhân viên Thu ngân'),
        ('Phó Bộ phận Lễ tân'),
        ('Nhân viên Lễ Tân'),
        ('Phó Bộ phận Chăm sóc khách hàng'),
        ('Chuyên viên Chăm sóc Khách hàng'),
        ('Quản lý chăm sóc khách hàng hậu phẫu'),
        ('Tổ trưởng Chăm sóc khách hàng hậu phẫu'),
        ('Chuyên viên Chăm sóc Khách hàng hậu phẫu'),
        ('Tổ trưởng Chăm sóc khách hàng hậu phẫu'),
        ('Chuyên viên Chăm sóc Khách hàng hậu phẫu'),
        ('Phó Bộ phận hộ lý'),
        ('Nhân viên Hộ lý'),
        ('Trưởng Bộ phận Bảo v ệ'),
        ('Nhân viên bảo vệ'),
        ('Tài xế');

Độc thân
Đã có gia đình
Ly dị
Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư
Cục Cảnh sát quản lý hành chính về trật tự xã hội